src/neptune_fetcher/read_only_project.py

Make functions in `ReadOnlyProject` that return `pandas.DataFrame` fetch data concurrently.
This speeds up data download by 20-70 percent, depending on the data layout.

`ReadOnlyProject` functions that fetch `DataFrame` are now concurrent.

---

src/neptune_fetcher/read_only_run.py
tests/integration/test_read_only_run.py

Note that this change does not modify the behaviour of `prefetch*()`, which do not operate on `Run._structure`.

`ReadOnlyRun.__getitem__` will now attempt to download missing fields

---

tests/populate_projects.py

Reverts neptune-ai/neptune-fetcher#112

Revert "Remove pool executor in populate projects"

---

src/neptune_fetcher/api/api_client.py
tests/unit/test_backoff_retry.py

Also modify the signature for clarity: `max_tries` vs `max_retries`. Add unit tests.

Handle exceptions in `backoff_retry`

---

dev_requirements.txt
pyproject.toml

Update neptune-api = "^0.10.0"

---

README.md
src/neptune_fetcher/read_only_run.py
tests/e2e/test_read_only_run.py

feat:  Add eager_load_attribute_definitions for ReadOnlyRun

---

.github/scripts/run-e2e-tests.sh

chore: Add utf8 characters in e2e project name

---

src/neptune_fetcher/alpha/__init__.py
src/neptune_fetcher/alpha/context.py
tests/alpha/test_context.py

feat: add alpha module with context handling

---

.github/license_header.txt
.pre-commit-config.yaml
src/neptune_fetcher/api/__init__.py
src/neptune_fetcher/api/api_client.py
src/neptune_fetcher/cache.py

chore: add license checking

---

src/neptune_fetcher/nql.py
src/neptune_fetcher/read_only_project.py
src/neptune_fetcher/read_only_run.py
tests/e2e/test_read_only_project.py

chore: use batching in ReadOnlyProject.fetch_read_only_experiments

---

.github/actions/run-tests/action.yml
.github/scripts/run-e2e-tests.sh
dev_requirements.txt

chore: Remove pytest-xdist

---

src/neptune_fetcher/alpha/filter.py
src/neptune_fetcher/alpha/internal/attribute.py
src/neptune_fetcher/alpha/internal/experiment.py
src/neptune_fetcher/alpha/internal/identifiers.py
src/neptune_fetcher/alpha/internal/types.py
src/neptune_fetcher/alpha/internal/util.py
tests/e2e/alpha/conftest.py
tests/e2e/alpha/test_attribute.py
tests/e2e/alpha/test_experiment.py

just a refactor moving the paging pattern to util and using it in fetch_experiments_sys/attribute_definitions

feat(alpha): extract paging logic to util

---

src/neptune_fetcher/alpha/internal/attribute.py
tests/e2e/alpha/test_attribute.py

chore: Use Generator in fetch attributes definitions.

---

.github/workflows/tests-e2e.yml

chore: fix e2e tests

---

tests/e2e/alpha/test_experiments.py

chore: test

---

src/neptune_fetcher/alpha/__init__.py
src/neptune_fetcher/alpha/experiments.py
src/neptune_fetcher/alpha/fetch_metrics.py
src/neptune_fetcher/alpha/internal/metric.py
tests/e2e/alpha/test_experiment.py
tests/e2e/alpha/test_fetch_metrics.py

chore(alpha): Implement fetch_metrics in alpha module

---

src/neptune_fetcher/alpha/experiment.py
src/neptune_fetcher/alpha/internal/attribute.py

chore: Return empty generator id definitions list is empty

---

src/neptune_fetcher/alpha/fetch_metrics.py
src/neptune_fetcher/alpha/internal/metric.py
tests/e2e/alpha/test_fetch_metrics.py
tests/unit/alpha/internal/test_metric.py
tests/unit/alpha/test_fetch_metrics.py

chore: Optimize fetch metrics

---

src/neptune_fetcher/alpha/__init__.py
src/neptune_fetcher/alpha/attribute.py
src/neptune_fetcher/alpha/experiment.py
src/neptune_fetcher/alpha/fetch_metrics.py
src/neptune_fetcher/alpha/filters.py
src/neptune_fetcher/alpha/internal/attribute.py
src/neptune_fetcher/alpha/internal/experiment.py
src/neptune_fetcher/alpha/internal/infer.py
src/neptune_fetcher/alpha/internal/metric.py
tests/e2e/alpha/internal/test_attribute.py
tests/e2e/alpha/internal/test_experiment.py
tests/e2e/alpha/internal/test_infer.py
tests/e2e/alpha/test_attribute.py
tests/e2e/alpha/test_experiment.py
tests/e2e/alpha/test_fetch_metrics.py

chore: Rename ExperimentFilter to Filter

---

src/neptune_fetcher/alpha/filters.py
tests/e2e/alpha/internal/test_experiment.py
tests/e2e/alpha/test_experiment.py

chore: Use iso format for dates in query

---

src/neptune_fetcher/alpha/fetch_metrics.py
tests/e2e/alpha/test_fetch_metrics.py
tests/unit/alpha/test_fetch_metrics.py

chore: Use multi index(experiment,step) in fetch_metrics

---

src/neptune_fetcher/alpha/filters.py
src/neptune_fetcher/alpha/internal/types.py
tests/unit/alpha/test_filters.py

chore: Filters validation

---

src/neptune_fetcher/alpha/experiment.py
src/neptune_fetcher/alpha/fetch_metrics.py
tests/unit/alpha/test_experiment.py
tests/unit/alpha/test_fetch_metrics.py

chore: Arguments validation

---

src/neptune_fetcher/alpha/fetch_metrics.py
tests/e2e/alpha/test_fetch_metrics.py
tests/unit/alpha/test_fetch_metrics.py

chore: Rename include_timestamp to include_time

---

src/neptune_fetcher/alpha/experiment.py
src/neptune_fetcher/alpha/internal/exception.py

chore: Improvements

---

src/neptune_fetcher/__init__.py

chore: Update import message

---

.github/workflows/tests-e2e.yml
tests/e2e/alpha/conftest.py
tests/e2e/alpha/generator.py
tests/e2e/alpha/runs/test_runs_list.py
tests/e2e/alpha/runs/test_runs_list_attributes.py

chore: add e2e for list_attributes and list_runs

---

.github/workflows/tests-e2e.yml
src/neptune_fetcher/alpha/internal/composition/fetch_table.py
src/neptune_fetcher/alpha/internal/output_format.py
tests/e2e/alpha/conftest.py
tests/e2e/alpha/generator.py
tests/e2e/alpha/runs/test_runs_fetch_runs_table.py
tests/e2e/alpha/runs/test_runs_list.py
tests/e2e/alpha/runs/test_runs_list_attributes.py
tests/unit/alpha/internal/test_output_format.py

chore: fetch runs table -tests

---

tests/e2e/alpha/generator.py
tests/e2e/alpha/runs/test_runs_fetch_metrics.py
tests/e2e/alpha/runs/test_runs_fetch_runs_table.py

chore: Implement tests for runs.fetch_metrics

---

README.md

- ~~[ ] Did you **update the CHANGELOG**? (not for test updates, internal changes/refactors or CI/CD setup)~~
- ~~[] Did you **ask the docs owner** to review all the user-facing changes?~~

alpha instructions, v1

---

dev_requirements.txt
pyproject.toml
src/neptune_fetcher/api/api_client.py
src/neptune_fetcher/cache.py
src/neptune_fetcher/fetchable.py
src/neptune_fetcher/fields.py
tests/e2e/test_dataframe_values.py
tests/e2e/test_log_and_fetch.py
tests/populate_projects.py
tests/unit/test_api_client.py

feat: Implement include_preview

---

CHANGELOG.md
README.md

Correct fetch_metrics() docs

---

src/neptune_fetcher/cache.py

This is done with respect to backend-side limits

Lower limits on path count / total length in FieldsCache

---

src/neptune_fetcher/alpha/filters.py

- [-] Did you **update the CHANGELOG**? (not for test updates, internal changes/refactors or CI/CD setup)

Fix name_in() docstring

---

src/neptune_fetcher/alpha/exceptions.py

[DOC-13: \[API\] Audit missing token/project messages](https://linear.app/neptuneai/issue/DOC-13/[api]-audit-missing-tokenproject-messages)

DOC-13: Tweak authentication error messages

---

src/neptune_fetcher/exceptions.py

Tweak exception messages. (Based on `ms/move-alpha-top-b`)
[PY-52: Review (& improve) all exceptions currently in use by `alpha`](https://linear.app/neptuneai/issue/PY-52/review-and-improve-all-exceptions-currently-in-use-by-alpha)

PY-52: Review & improve all exceptions used by Alpha

---

README.md
docs/legacy/api_reference.md
docs/legacy/usage.md

Update docs for Scale "soft-GA" and promoting the Alpha API to top-level.

Update docs for Alpha promotion

---

pyproject.toml
src/neptune_fetcher/alpha/__init__.py
src/neptune_fetcher/alpha/filters.py
src/neptune_fetcher/alpha/internal/composition/download_files.py
src/neptune_fetcher/alpha/internal/env.py
src/neptune_fetcher/alpha/internal/output_format.py
src/neptune_fetcher/alpha/internal/retrieval/attribute_types.py
src/neptune_fetcher/alpha/internal/retrieval/files.py
src/neptune_fetcher/alpha/runs.py
tests/e2e/alpha/internal/composition/test_download_files.py
tests/e2e/alpha/internal/conftest.py
tests/e2e/alpha/internal/data.py
tests/e2e/alpha/internal/retrieval/test_attributes.py
tests/e2e/alpha/internal/retrieval/test_files.py
tests/e2e/alpha/internal/retrieval/test_search.py
tests/e2e/alpha/internal/retrieval/test_series.py
tests/e2e/alpha/internal/test_attributes.py
tests/e2e/alpha/internal/test_experiments.py
tests/unit/alpha/internal/test_output_format.py

feat(alpha): download files

---

pyproject.toml

Bump neptune-api to 0.22.0
